// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjz1HZlWDu1hrI5vLJfP6XHyJMHfSpGs0',
    appId: '1:892910728052:web:05aaefd9c563c0b3103221',
    messagingSenderId: '892910728052',
    projectId: 'chatapp-257f2',
    authDomain: 'chatapp-257f2.firebaseapp.com',
    storageBucket: 'chatapp-257f2.appspot.com',
    measurementId: 'G-FPWXYREJM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzpDHqOIHVxT-Vphgcs21N2QC0RbEP6nY',
    appId: '1:892910728052:android:7a4a18d71b83df0e103221',
    messagingSenderId: '892910728052',
    projectId: 'chatapp-257f2',
    storageBucket: 'chatapp-257f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2w96J222S3or1xPHt_a_aOQPDCbY-_kw',
    appId: '1:892910728052:ios:a6c012465ea3390c103221',
    messagingSenderId: '892910728052',
    projectId: 'chatapp-257f2',
    storageBucket: 'chatapp-257f2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2w96J222S3or1xPHt_a_aOQPDCbY-_kw',
    appId: '1:892910728052:ios:a6c012465ea3390c103221',
    messagingSenderId: '892910728052',
    projectId: 'chatapp-257f2',
    storageBucket: 'chatapp-257f2.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjz1HZlWDu1hrI5vLJfP6XHyJMHfSpGs0',
    appId: '1:892910728052:web:1fa7246bbcd34ffa103221',
    messagingSenderId: '892910728052',
    projectId: 'chatapp-257f2',
    authDomain: 'chatapp-257f2.firebaseapp.com',
    storageBucket: 'chatapp-257f2.appspot.com',
    measurementId: 'G-HN4YJ03CB1',
  );
}
